#!/usr/bin/env bash

#TODAY="$(date "+%F")"
WORKING_DIR="$HOME/Projects/journal_publisher"
OUTPUT_DIR="$WORKING_DIR/_site"
LOCATION="$WTTR_LOCATION"

usage() {
    cat <<HEREDOC
    Reguires: aha awk figlet lolcat cowsay
HEREDOC
}

while getopts "t:h" opt; do
    case "$opt" in
        *)
            usage
            exit
            ;;
    esac
done
shift $((OPTIND - 1))


header() {
    cat << HEREDOC
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <style>
        body {
          background-color: #121212;
          font-family: 'Noto Sans Mono', monospace;
          font-size: 12px;
          color: #E0E0E0;
        }
        a:link {
          color: #E0E0E0;
        }
        a:visited,a:hover {
          color: #888888;
        }
        main {
          max-width: 60em;
          /* margin: 0 auto; */
        }
        code {
          font-family: monospace;
          color: #B0B0B0;
        }
        li {
          list-style-type: none;
        }
        li::before {
          content: "- ";
        }
        .ascii-art {
          font-size: 10px;
          line-height: 1.0;
          white-space: pre; /* Preserves spaces and line breaks */
          display: block; /* Spans are inline by default, making it block can help with layout */
        }
        .ascii-text {
          white-space: pre-wrap; /* Preserves spaces and line breaks */
        }
    </style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="fonts.googleapis.com" rel="stylesheet">
<link rel="stylesheet" href="./css/html-ansi.css">
</head>
<body>
<main>
HEREDOC
}

title() {
    printf '%s\n' "<h1>$*</h1>"
}

footer() {
    cat << HEREDOC
</main>
</body>
</html>
HEREDOC
}

paragraph() {
    printf '%s\n' "<p class='ascii-text'>$*</p>"
}

title_figlet() {
    printf '%s' "<p class='ascii-art'>"
    echo "$*" | figlet -w 100| lolcat --seed=1337 -ft | aha -n -b -r
    printf '%s\n' "</p>"

}

moon_phase_ascii() {
    local destination="${OUTPUT_DIR}/moon_phases/moon_phase-$TODAY"
    if  [[ -s "$destination" ]]; then #&& [[ "$(stat -c %y "$destination" | awk '{print $1}')" == "$TODAY" ]]; then
        #echo "moon phase cache hit" >&2
        cat "$destination"
    else
        curl --silent "wttr.in/Moon@$TODAY" | sed 's/Follow .*@igor_chubin.* for wttr\.in updates//' > "$destination"
        cat "$destination"
    fi
}

moon_phase_html() {
    printf '%s\n' "<span class='ascii-art'>"
    moon_phase_ascii | aha -n -b
    printf '%s\n' "</span>"
}


href() {
    printf '%s\n' "<a href=$*.html>$*</a>"
}

ul() {
    printf '%s\n' "<ul>$*</ul>"
}

list_item() {
    printf '%s\n' "<li>$*</li>"
}

kilroysay() {
    printf '%s' "<span class='ascii-art'>"
    echo "$*" | cowsay -f "$WORKING_DIR/tools/kilroy.cow" | aha -n -b -r
    printf '%s' "</span>"
}

_cowsay() {
    printf '%s' "<span class='ascii-art'>"
    echo "$*" | cowsay | aha -n -b -r
    printf '%s' "</span>"
}

entries=($(nb interstitial_journal/ | grep --color=never -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' | sort -r))

#make index.html
(
    header
    title_figlet "EVIL BOBS DIARY"
    paragraph "Entries:" "$(ul "$(for entry in "${entries[@]}"; do list_item "$(href "$entry")"; done)")"
    kilroysay "Kilroy was here"
    footer
) > "${OUTPUT_DIR}/index.html"

# make journal entry pages
for d in "${entries[@]}"; do
    TODAY="$d"
    if ! [[ -a "$OUTPUT_DIR" ]];then mkdir "$OUTPUT_DIR"; fi
    (
        header
        title_figlet "$(date -d "$TODAY" -R | awk '{print $1, $2, $3, $4}')"
        moon_phase_html
        paragraph "$(nb export pandoc interstitial_journal/$d --from markdown --to html)" # | sed --regexp-extended 's/(https?:\/\/\S*)([\s|<])/\["\1"\]\(\1\)/gm')"
        #paragraph "$(nb show interstitial_journal/$d)"
        #paragraph "$(nb show interstitial_journal/$d | aha -n -b)"
        footer
    ) > "${OUTPUT_DIR}/${d}.html"
done

push_to_remote() {
    pushd "$WORKING_DIR" && git add * && git commit -am "publish" && git push origin master
    popd
}
push_to_remote

