#!/usr/bin/env bash

#TODAY="$(date "+%F")"
WORKING_DIR="$HOME/Projects/journal_publisher"
OUTPUT_DIR="$WORKING_DIR/_site"
LOCATION="$WTTR_LOCATION"

usage() {
    cat <<HEREDOC
    Reguires: aha awk figlet lolcat cowsay
HEREDOC
}

while getopts "t:h" opt; do
    case "$opt" in
        *)
            usage
            exit
            ;;
    esac
done
shift $((OPTIND - 1))

source ./partials/header.sh
source ./partials/footer.sh

title() {
    printf '%s\n' "<h1>$*</h1>"
}

paragraph() {
    printf '%s\n' "<p class='ascii-text'>$*</p>"
}

title_figlet() {
    printf '%s' "<p class='ascii-art'>"
    echo "$*" | figlet -w 100| lolcat --seed=1337 -ft | aha -n -b -r
    printf '%s\n' "</p>"

}

moon_phase_ascii() {
    local destination="${OUTPUT_DIR}/moon_phases/moon_phase-$TODAY"
    if  [[ -s "$destination" ]]; then #&& [[ "$(stat -c %y "$destination" | awk '{print $1}')" == "$TODAY" ]]; then
        #echo "moon phase cache hit" >&2
        cat "$destination"
    else
        curl --silent "wttr.in/Moon@$TODAY" | sed 's/Follow .*@igor_chubin.* for wttr\.in updates//' > "$destination"
        cat "$destination"
    fi
}

moon_phase_html() {
    printf '%s\n' "<span class='ascii-art'>"
    moon_phase_ascii | aha -n -b
    printf '%s\n' "</span>"
}


href() {
    printf '%s\n' "<a href=$*.html>$*</a>"
}

ul() {
    printf '%s\n' "<ul>$*</ul>"
}

list_item() {
    printf '%s\n' "<li>$*</li>"
}

kilroysay() {
    printf '%s' "<span class='ascii-art'>"
    echo "$*" | cowsay -f "$WORKING_DIR/tools/kilroy.cow" | aha -n -b -r
    printf '%s' "</span>"
}

_cowsay() {
    printf '%s' "<span class='ascii-art'>"
    echo "$*" | cowsay | aha -n -b -r
    printf '%s' "</span>"
}

entries=($(nb interstitial_journal/ | grep --color=never -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' | sort -r))

#make index.html
(
    header
    title_figlet "EVIL BOBS DIARY"
    paragraph "Entries:" "$(ul "$(for entry in "${entries[@]}"; do list_item "$(href "$entry")"; done)")"
    kilroysay "Kilroy was here"
    footer
) > "${OUTPUT_DIR}/index.html"

# make journal entry pages
for d in "${entries[@]}"; do
    TODAY="$d"
    if ! [[ -a "$OUTPUT_DIR" ]];then mkdir "$OUTPUT_DIR"; fi
    (
        header
        title_figlet "$(date -d "$TODAY" -R | awk '{print $1, $2, $3, $4}')"
        moon_phase_html
        paragraph "$(nb export pandoc interstitial_journal/$d --from markdown --to html)" # | sed --regexp-extended 's/(https?:\/\/\S*)([\s|<])/\["\1"\]\(\1\)/gm')"
        #paragraph "$(nb show interstitial_journal/$d)"
        #paragraph "$(nb show interstitial_journal/$d | aha -n -b)"
        footer
    ) > "${OUTPUT_DIR}/${d}.html"
done

push_to_remote() {
    pushd "$WORKING_DIR" && git add * && git commit -am "publish" && git push origin master
    popd
}
push_to_remote

