#!/usr/bin/env bash
set -e

#TODAY="$(date "+%F")"
WORKING_DIR="$HOME/Projects/journal_publisher"
OUTPUT_DIR="$WORKING_DIR/_site"
INCLUDES_DIR="$WORKING_DIR/includes"
LOCATION="$WTTR_LOCATION"
FILE_NAME="$(today).md"

usage() {
    cat <<HEREDOC
    Reguires: aha awk figlet lolcat cowsay
HEREDOC
}

preflight() {
    local prereqs=( "cowsay" "figlet" "lolcat" "aha" )
    for req in "${prereqs[@]}"; do
        if ! command -v "$req" > /dev/null 2>&1; then
            echo "Requires $req to be installed."
            exit 1
        fi
    done
}

title() {
    printf '%s\n' "<h1>$*</h1>"
}

flow() {
    printf '%s\n' "<div class="flow">$*</div>"
}

div() {
    local classes="$1"
    shift
    printf '%s\n' "<div class=\"$classes\">$*</div>"
}

paragraph() {
    printf '%s\n' "<p class='ascii-text'>$*</p>"
}

title_figlet() {
    printf '%s' "<p class='ascii-art'>"
    echo "$*" | figlet -w 100| lolcat --seed=1337 -ft | aha -n -b -r
    printf '%s\n' "</p>"

}

moon_phase_ascii() {
    local destination="${OUTPUT_DIR}/moon_phases/moon_phase-$TODAY"
    if  [[ -s "$destination" ]]; then #&& [[ "$(stat -c %y "$destination" | awk '{print $1}')" == "$TODAY" ]]; then
        #echo "moon phase cache hit" >&2
        cat "$destination"
    else
        curl --silent "wttr.in/Moon@$TODAY" | sed 's/Follow .*@igor_chubin.* for wttr\.in updates//' > "$destination"
        cat "$destination"
    fi
}

moon_phase_html() {
    printf '%s\n' "<span class='ascii-art'>"
    moon_phase_ascii | aha -n -b
    printf '%s\n' "</span>"
}

href() {
    printf '%s\n' "<a href=$*.html>$*</a>"
}

ul() {
    printf '%s\n' "<ul>$*</ul>"
}

list_item() {
    printf '%s\n' "<li>$*</li>"
}

kilroysay() {
    printf '%s' "<span class='ascii-art'>"
    echo "$*" | cowsay -f "$WORKING_DIR/tools/kilroy.cow" | aha -n -b -r
    printf '%s' "</span>"
}

_cowsay() {
    printf '%s' "<span class='ascii-art'>"
    echo "$*" | cowsay | aha -n -b -r
    printf '%s' "</span>"
}

push_to_remote() {
    if [[ "$PUSH" ]]; then
        git add *
        git commit -am "publish" && git push origin master
    fi
}

parse_date() {
    case "$OSTYPE" in
        darwin*) date -j -f "%Y-%m-%d" "$1" +"%a, %d %b %Y" ;;
        linux*)  date -d "$1" +"%a, %d %b %Y" ;;
        msys*)   echo "Windows?"; exit 1 ;;
        *)       echo "Cannot parse dates"; exit 1 ;;
    esac
}



main() {
    preflight

    pushd "$WORKING_DIR"

    source ./partials/header.sh
    source ./partials/footer.sh
    cp -r  "$INCLUDES_DIR"/* "$OUTPUT_DIR"/

    entries=($(nb list interstitial_journal/ | grep --color=never -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' | sort -r))

     #make index.html
    (
        header
        title_figlet "EVIL BOBS DIARY"
        div "flow" "<pre class="ascii-banner">$(echo "This is my Interstitial Journal. It's my thoughts and useful things I want to remember." | comment-banner)" "</pre>"
        #div "$(paragraph "Entries:" "$(ul "$(for entry in "${entries[@]}"; do list_item "$(href "$entry")"; done)")")"

        for entry in "${entries[@]}"; do
            TODAY="${entry}"
            #if ! [[ -a "$OUTPUT_DIR" ]];then mkdir "$OUTPUT_DIR"; fi
            title_figlet "$(parse_date "${TODAY}" -R | awk '{print $1, $2, $3, $4}')"
            moon_phase_html
            href "$entry"
            paragraph "$(nb export pandoc interstitial_journal/${entry}.md --from markdown --to html)"
        done

        kilroysay "Kilroy was here"
        footer
        ) > "${OUTPUT_DIR}/index.html"

        # make journal entry pages
        for entry in "${entries[@]}"; do
            TODAY="${entry}"
            if ! [[ -a "$OUTPUT_DIR" ]];then mkdir "$OUTPUT_DIR"; fi
            (
                header
                title_figlet "$(parse_date "${TODAY}" -R | awk '{print $1, $2, $3, $4}')"
                moon_phase_html
                paragraph "$(nb export pandoc interstitial_journal/${entry}.md --from markdown --to html)"
                footer
                ) > "${OUTPUT_DIR}/${entry}.html"
            done
            push_to_remote

            popd
        }

while getopts "t:hp" opt; do
    case "$opt" in
        p)
            PUSH=1
            ;;
        *)
            usage
            exit
            ;;
    esac
done
shift $((OPTIND - 1))

main "$@"
